server:
  port: 8081

spring:
  application:
    name: userService
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/users_db}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:file:.env[.properties]

api:
  security:
    token:
      secret: ${JWT_SECRET:mySuperSecretKey123!}
      issuer: ${JWT_ISSUER:user-service}
